### ISSUE TITLE
Default methods section is not explanatory

### ISSUE THREAD

**Issue by alexpdp7** [winterbe/java8-tutorial#14]
The example does not have any meaningful utility.

The Java tutorial explanation at https://docs.oracle.com/javase/tutorial/java/IandI/defaultmethods.html is much better:

> Default methods enable you to add new functionality to the interfaces of your libraries and ensure binary compatibility with code written for older versions of those interfaces.

**Comment by winterbe** [comment]
I respect your point of view and invite you and everyone else to read the official java language documentation, if you can spend the time. The main purpose of my guide is to provide a quick example-driven overview of the new language and api features in Java 8 without covering every feature in full length.

I close this issue since you doesn't provide meaningful improvement suggestions. However I gladly review any pull request for improvements to my guide.
