### ISSUE TITLE
Lambda expressions section's example is not illustrative

### ISSUE THREAD

**Issue by alexpdp7** [winterbe/java8-tutorial#15]
As String implements Comparable, Collections.sort with no parameters will perform the same action that all examples in the section, in a more concise and clear way.

Again, the Java Tutorial provides much more illustrative examples at:

https://docs.oracle.com/javase/tutorial/java/javaOO/lambdaexpressions.html

Sorting by specific fields is another way to provide a better example (which also flows well to explain method references).

**Comment by kkamkou** [comment]
+1

**Comment by winterbe** [comment]
> Collections.sort with no parameters will perform the same action that all examples in the section, in a more concise and clear way.

That's not exactly the case, because in my example I choose to compare b to a, not a to b. So the resulting order will be descending instead of the default ascending order, if you omit a custom comparator.

I decided to use sorting do demonstrate lambda expressions, because everyone is already familiar with this kind of stuff. The intention of this section is not to demonstrate the best solutions for sorting but to give a quick overview of the syntax of lambda expressions.

My guide should by no means replace the official docs, it's meant to serve as a quick introduction to Java 8 - something that the official docs cannot provide due it's length and details.
