### ISSUE TITLE
Default methods description

### ISSUE THREAD

**Issue by tmescic** [winterbe/java8-tutorial#17]
I think that should mention why are default methods useful (because you can now extend interfaces without breaking existing code that is implementing those interfaces).

**Comment by rage-shadowman** [comment]
...and why not an explanation of why you should never use them too? They are a code smell, like static variables on interfaces. They hide where a function is coming from. If you have a class that extends another class and implements an interface, then at first glance you would assume this undefined function comes from the parent class. They have their purpose, but IMO, as a general rule you should never use default functions.

**Comment by jshook** [comment]
@rage-shadowman I believe that your last statement on the matter is dissonant. Default methods on interfaces do simplify a pattern that is less obvious when it is implemented in concrete logic. In fact, some of the work with functional interfaces in Java 8 would have been nigh-unexplainable and in some cases difficult to implement at all without them. I'm not saying that I'm a big fan. I'm only saying that you can't say they should never be used if you agree that they have their purpose.

**Comment by rage-shadowman** [comment]
@jshook Read again: "as a general rule".

The dissonance was supposed to be obvious. As it is in the following quote:
> Always remember, never use always or never.
> \- Someone else

Their purpose is simply for when you are modifying an interface that is used by another piece of code that you have no control over (ie: you have no other choice). Otherwise, IMO, you are just being lazy and making your code harder to maintain.

So again... And this is simply my opinion (\<sarcasm>feel free to ignore it at your own peril\</sarcasm>)... As a **general** rule... You should **NEVER** use them!!!

That said, a good explanation as to where they might be necessary and the opinions both for and against them (let the readers decide whether or not to use it in their own code), would be a good addition, IMO.

**Comment by winterbe** [comment]
Every language feature has it's pros and cons, so does default interface methods. I don't think you should abandon them all, but that's just my opinion. 

However the main purpose of this tutorial is to demonstrate all the features introduced in Java 8 without rating it's usefulness. That's why I'm not going to add additional explanations to this topic. Thanks for you understanding.
