### ISSUE TITLE
Primitive streams

### ISSUE THREAD

**Issue by erosb** [winterbe/java8-tutorial#22]
I think it would be worthy to give a pew paragraphs long section about primitive streams too (why they matter and how to use them). I'll try to create a PR for it (as my time permits).

**Comment by winterbe** [comment]
Streams are extremely powerful, they deserve it's own tutorial. That's why I wrote a separate tutorial, however it's not yet available on Github but only on my blog: http://winterbe.com/posts/2014/07/31/java8-stream-tutorial-examples/

I guess I should add the link to the appropriate stream section. But going more into details about streams in this general Java 8 tutorial would be overkill.
